"""strategy_state, bot_positions

Revision ID: 4bdfc31f8ac5
Revises: 140cfcc58de4
Create Date: 2026-08-16 22:01:46.419674

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4bdfc31f8ac5'
down_revision: str | None = '140cfcc58de4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True),
              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy', 'symbol', name='uq_bot_position_strategy_symbol')
    )
    op.create_table('strategy_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('halt_reason', sa.Text(), nullable=True),
    sa.Column('allocation_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('day_start_equity_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True),
              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_state')
    op.drop_table('bot_positions')
    # ### end Alembic commands ###
