"""mode_b: day_plans, state, trades

Revision ID: 6b7b7094b6b2
Revises: 9756e486d7d5
Create Date: 2026-08-16 23:13:54.000355

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '6b7b7094b6b2'
down_revision: str | None = '9756e486d7d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True),
              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_date')
    )
    op.create_table('mode_b_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('tape_text', sa.Text(), nullable=False),
    sa.Column('counters_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True),
              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_date')
    )
    op.create_table('mode_b_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('setup', sa.String(length=48), nullable=False),
    sa.Column('off_plan', sa.Boolean(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('realized_r', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mode_b_trades')
    op.drop_table('mode_b_state')
    op.drop_table('day_plans')
    # ### end Alembic commands ###
