"""initial schema: snapshots

Revision ID: 942a882646fd
Revises: 
Create Date: 2026-08-16 18:23:09.494795

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '942a882646fd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('positions_json', sa.Text(), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'snapshot_date', name='uq_snapshot_account_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots')
    # ### end Alembic commands ###
