"""plaid_items

Revision ID: fc45d68311a1
Revises: 6b7b7094b6b2
Create Date: 2026-08-17 12:24:50.684491

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'fc45d68311a1'
down_revision: str | None = '6b7b7094b6b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.String(length=128), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True),
              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plaid_items')
    # ### end Alembic commands ###
